
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (1, 'teste', 'te');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (121, 'ESTA��O ADUANEIRA INTERIOR DE COL�MBIA', 'EADI-Col�mbia-SP');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (167, 'ESTA��O ADUANEIRA INTERIOR DE UBERABA', 'EADI-Multiterminais Uberaba-MG');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (106, 'teste', 'teste');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (107, 'teste', 'teste');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (108, 'teste', 'teste');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (111, 'teste', 'teste');
INSERT INTO DBSISTRU.TB_UNIDADE_ORG(CO_SEQ_INTERNO_UORG,NO_UNIDADE_ORG, SG_UNIDADE_ORG) VALUES (109, 'teste', 'teste');

INSERT INTO RH.TB_LOTACAO_SERVIDOR(CO_SEQ_LOTACAO_SERVIDOR, DT_FIM_LOTACAO, DT_INICIO_LOTACAO, ID_PESSOA_SERVIDOR,CO_INTERNO_UORG) VALUES (2550, null, '2015-08-01', 11, 167);

INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('1',1,123456,'Mario Melo','03232663125');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('2',2,123456,'Livia Soares','33653580994');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('6',7,12345678,'Herbert Viana','33653580994');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('4',5,1234567,'Takuma Iokino','33653580994');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('3',4,1234567,'Yori Yagame','33653580994');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('7',4,123455,'Maria -)','1234567890');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('8',5,12356974,'Batosai o retalhador','39115253201');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('9',8,58964145,'Power Ranger Prateado','12865005160');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('10',1,12345687,'Cabra Macho','01142764125');
INSERT INTO RH.TB_SERVIDOR (ID_PESSOA_SERVIDOR,CO_SITUACAO_FUNCIONAL,NU_SIAPE,NO_SERVIDOR,NU_CPF) VALUES ('11',1,10101515,'Teste','01142764125');

INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (1, 'S', 'ATIVO PERMANENTE');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (2, 'S', 'APOSENTADO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (3, 'S', 'REQUISITADO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (4, 'S', 'NOMEADO CARGO COMIS.');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (8, 'S', 'CEDIDO QUE PROGRIDE');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (9, 'S', 'CEDIDO QUE NAO PROGRIDE');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (11, 'S', 'EXCEDENTE A LOTACAO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (14, 'S', 'REQ.DE OUTROS ORGAOS');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (18, 'S', 'EXERC DESCENT CARREI');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (19, 'S', 'EXERCICIO PROVISORIO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (20, 'S', 'EXERCICIO �7 ART. 93 8112');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (66, 'S', 'ESTAGIARIO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (93, 'S', 'BENEFICIARIO PENSAO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (94, 'S', 'COLABORADOR EXTERNO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (95, 'S', 'TERCEIRIZADO');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL(CO_SEQ_SITUACAO_FUNCIONAL, ST_REGISTRO_ATIVO, DS_SITUACAO_FUNCIONAL) VALUES (99, 'S', 'OUTROS');


INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (1,'Ativo Permanente');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (3,'Requisitado');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (2,'Aposentado');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (4,'Nomeado Cargo Comissionado');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (6,'Excedente a Lotação');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (5,'Cedido');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (7,'Req. De outros Órgãos');
INSERT INTO RH.TD_SITUACAO_FUNCIONAL (CO_SEQ_SITUACAO_FUNCIONAL,DS_SITUACAO_FUNCIONAL) VALUES (8,'Exercício Provisório');

INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(1,1,106,'2015-05-18 14:51:07','2015-05-18 14:51:13');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(2,1,107,'2015-05-18 14:53:10','2015-05-18 14:53:13');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(3,1,108,'2015-05-18 18:15:18','2015-05-18 18:15:20');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(4,3,111,'2015-05-19 10:49:22','2015-05-19 10:49:23');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(6,2,108,'2015-05-19 10:51:14','2015-05-19 10:51:16');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(5,4,109,'2015-05-19 10:49:50','2015-05-19 10:49:52');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(7,7,106,'2015-05-19 11:31:55','2015-05-19 11:31:57');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(8,8,107,'2015-05-19 11:36:27','2015-05-19 11:36:29');
INSERT INTO RH.TB_LOTACAO_SERVIDOR (CO_SEQ_HIST_LOTACAO,CO_SEQ_SERVIDOR,CO_SEQ_INTERNO_UORG,DT_INICIO,DT_FIM) VALUES(9,6,106,'2015-05-19 11:37:06','2015-05-19 11:37:08');


INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (6,'terceiroGrauIncompleto');
INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (5,'terceiroGrauCompleto');
INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (4,'segundoGrauCompleto');
INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (3,'segundoGrauIncompleto');
INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (2,'primeiroGrauCompleto');
INSERT INTO RH.TD_ESCOLARIDADE (CO_SEQ_ESCOLARIDADE,DS_ESCOLARIDADE) VALUES (1,'Primeiro Grau Incompleto');

INSERT INTO RH.TB_CURSO (CO_SEQ_CURSO, DS_CURSO) VALUES (1, 'SISTEMAS DA INFORMACAO');
INSERT INTO RH.TB_CURSO (CO_SEQ_CURSO, DS_CURSO) VALUES (2, 'Biologia');
INSERT INTO RH.TB_CURSO (CO_SEQ_CURSO, DS_CURSO) VALUES (3, 'Medicina');


INSERT INTO RH.TD_GRAU_PARENTESCO (CO_SEQ_GRAU_PARENTESCO, DS_GRAU_PARENTESCO) VALUES (1, 'Pai');


INSERT INTO RH.TD_DEFICIENCIA (CO_SEQ_DEFICIENCIA, DS_DEFICIENCIA) VALUES (1, 'Deficiencia');

INSERT INTO RH.TB_INSTITUICAO_ENSINO (CO_SEQ_INSTITUICAO_ENSINO, DS_INSTITUICAO_ENSINO) VALUES (1,'Instituicao');
INSERT INTO RH.TB_INSTITUICAO_ENSINO (CO_SEQ_INSTITUICAO_ENSINO, DS_INSTITUICAO_ENSINO) VALUES (2,'Anvisa');
INSERT INTO RH.TD_TIPO_CURSO (CO_SEQ_TIPO_CURSO, DS_TIPO_CURSO, TP_GRUPO_CURSO)  VALUES(1, 'tipo', 1);


INSERT INTO RH.TB_TIPO_TELEFONE(CO_SEQ_TIPO_TELEFONE, DS_TIPO_TELEFONE) values (0, 'n/a');


INSERT INTO DBCORPORATIVO.TB_PESSOA_FISICA (ID_PESSOA_FISICA, NO_PESSOA_FISICA, NU_CPF) VALUES('AAAABBB', 'mario', '11111111111');
INSERT INTO DBCORPORATIVO.TB_PESSOA_FISICA (ID_PESSOA_FISICA, NO_PESSOA_FISICA, NU_CPF) VALUES('AAAABBBC', 'mario', '03232663125');

INSERT INTO RH.TD_TIPO_PARTICIPACAO (CO_SEQ_TIPO_PARTICIPACAO, NO_TIPO_PARTICIPACAO, ST_REGISTRO_ATIVO) VALUES(0, 'Participante', 'S' );
INSERT INTO RH.TD_TIPO_PARTICIPACAO (CO_SEQ_TIPO_PARTICIPACAO, NO_TIPO_PARTICIPACAO, ST_REGISTRO_ATIVO) VALUES(1, 'Participante', 'S' );

INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(0, 'Curso a distância', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(1, 'Curso Presencial	', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(2, 'Conferencia', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(3, 'Congresso', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(4, 'Disciplina', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(5, 'Encontro', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(6, 'Estágio', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(7, 'Fórum', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(8, 'Oficina', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(0, 'Reunião', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(10, 'Seminário', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(11, 'Treinamento', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(12, 'Palestra', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(13, 'Painel', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(14, 'Simpósio', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(15, 'Visita técnica', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(16, 'Workshop', 'S' );
INSERT INTO RH.TD_TIPO_CAPACITACAO (CO_SEQ_TIPO_CAPACITACAO, NO_TIPO_CAPACITACAO, ST_REGISTRO_ATIVO) VALUES(17, 'Outros.', 'S' );




INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(1, '0089', 'Lic. Motiv. Doen. Pes. Fam. Após 60 dias S/Remuneração - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(2, '0090', 'Lic. por Motivo de Doença em Pessoa da Família - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(3, '0227', 'HIST. EST L1711/52- Lic. Doença Pessoa Família', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(4, '0088', 'Lic. Motivo Afastamento Cônjuge - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(5, '0224', 'HIST. EST L1711/52- Lic. Acompanhar Cônjuge', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(6, '0079', 'Lic. Atividade Política Com Remuneração - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(7, '0080', 'Lic. Atividade Política Sem Remuneração - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(8, '0094', 'Penalidade Suspensão - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(9, '0243', 'HIST. EST L1711/52- Prisão Definitiva Reclusão', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(10, '0008', 'Afas. Curso de Formação Opção Auxílio Financeiro - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(11, '0009', 'Afas. Curso Formação Opção Cargo EfetivoC/ Remun. - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(12, '0066', 'Falta - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(13, '0077', 'Lic. Incentivada Sem Remuneração - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(14, '0078', 'Lic. Incentivada Sem Remun. Prorrog - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(15, '0085', 'Lic. Tratar de Interesses Particulares - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(16, '0014', 'Afas. Exer. Mand. Elet. Gov e Vice-Gov Dep S/Rem - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(17, '0015', 'Afas. Exer. Mand. Elet. Prefeito C/Remun. - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(18, '0016', 'Afas. Exer. Mand. Elet. Prefeito S/Remun. - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(19, '0017', 'Afas. Exer. Mand. Elet. Senador 4 anos S/Remun - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(20, '0018', 'Afas. Exer. Mand. Elet. Senador 8 anos S/Remun - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(21, '0019', 'Afas. Exer. Mand. Elet. Vereador C/Remun - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(22, '0020', 'Afas. Exer. Mand. Elet. Vereador S/Remun - EST', 'S' );
INSERT INTO RH.TD_AFASTAMENTO (CO_SEQ_TIPO_AFASTAMENTO, NU_CODIGO_AFASTAMENTO, DS_AFASTAMENTO, ST_REGISTRO_ATIVO) VALUES(23, '0082', 'Lic. Desemp. Mand. Clas. Com Ressarcimento - EST', 'S' );

INSERT INTO RH.TD_MOTIVO_DESLIGAMENTO(CO_SEQ_MOTIVO_DESLIGAMENTO, ST_REGISTRO_ATIVO, DS_MOTIVO_DESLIGAMENTO) VALUES (1, 'S', 'teste');

INSERT INTO RH.TD_NIVEL_CARGO(CO_SEQ_NIVEL_CARGO, ST_REGISTRO_ATIVO, NO_NIVEL_CARGO) VALUES (1, 'S', 'teste');


INSERT INTO RH.TD_QUADRO_FUNCIONAL(CO_SEQ_QUADRO_FUNCIONAL, ST_REGISTRO_ATIVO, NO_QUADRO_FUNCIONAL) VALUES (1, 'S', 'Efetivo');
INSERT INTO RH.TD_QUADRO_FUNCIONAL(CO_SEQ_QUADRO_FUNCIONAL, ST_REGISTRO_ATIVO, NO_QUADRO_FUNCIONAL) VALUES (2, 'S', 'Espec�fico');
INSERT INTO RH.TD_QUADRO_FUNCIONAL(CO_SEQ_QUADRO_FUNCIONAL, ST_REGISTRO_ATIVO, NO_QUADRO_FUNCIONAL) VALUES (3, 'S', 'SemV�nculo');
INSERT INTO RH.TD_QUADRO_FUNCIONAL(CO_SEQ_QUADRO_FUNCIONAL, ST_REGISTRO_ATIVO, NO_QUADRO_FUNCIONAL) VALUES (999, 'S', 'Outros');

INSERT INTO RH.TD_CARGO(CO_SEQ_CARGO, ST_REGISTRO_ATIVO, NO_CARGO, CO_QUADRO_FUNCIONAL) VALUES (1, 'S', 'ANALISTA ADMINISTRATIVO', 1);
INSERT INTO RH.TD_CARGO(CO_SEQ_CARGO, ST_REGISTRO_ATIVO, NO_CARGO, CO_QUADRO_FUNCIONAL) VALUES (2, 'S', 'MEDICO', 2);
INSERT INTO RH.TD_CARGO(CO_SEQ_CARGO, ST_REGISTRO_ATIVO, NO_CARGO, CO_QUADRO_FUNCIONAL) VALUES (3, 'S', 'ESTAGIÁRIO', 999);
INSERT INTO RH.TD_CARGO(CO_SEQ_CARGO, ST_REGISTRO_ATIVO, NO_CARGO, CO_QUADRO_FUNCIONAL) VALUES (4, 'S', null, null);
INSERT INTO RH.TD_CARGO(CO_SEQ_CARGO, ST_REGISTRO_ATIVO, NO_CARGO, CO_QUADRO_FUNCIONAL) VALUES (5, 'S', 'SEM VÍNCULO', 3);

INSERT INTO RH.TB_DADOS_FUNCIONAIS(ID_PESSOA_SERVIDOR, DT_DESLIGAMENTO, DT_DOU, DT_EFETIVO_EXERCICIO, DT_PORTARIA_NOMEACAO, DS_OBSERVACAO_SEM_VINCULO, ST_DESLIGADO, 
            NU_PORTARIA_NOMEACAO, CO_CARGO, CO_MOTIVO_DESLIGAMENTO, CO_NIVEL_CARGO, CO_PADRAO) VALUES ('11', '2015-08-11', '2015-08-15', '2015-08-15', 
            '2015-08-01', null, 'N',  5, 1, 1, null,  2);

INSERT INTO RH.TD_CLASSE (CO_SEQ_CLASSE, NO_CLASSE, ST_REGISTRO_ATIVO) VALUES(1, 'A', 'S');
INSERT INTO RH.TD_CLASSE (CO_SEQ_CLASSE, NO_CLASSE, ST_REGISTRO_ATIVO) VALUES(2, 'B', 'S');
INSERT INTO RH.TD_CLASSE (CO_SEQ_CLASSE, NO_CLASSE, ST_REGISTRO_ATIVO) VALUES(3, 'E', 'S');


INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(3, 3, 'EI', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(45, 1, 'AIV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(63, 3, 'EIV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(49, 2, 'BII', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(1, 2, 'BI', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(61, 3, 'EII', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(51, 2, 'BIV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(44, 1, 'AIII', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(64, 3, 'EV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(46, 1, 'AV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(2, 1, 'AI', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(52, 2, 'BV', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(62, 3, 'EIII', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(50, 2, 'BIII', 'S');
INSERT INTO RH.TD_PADRAO (CO_SEQ_PADRAO, CO_CLASSE, NO_PADRAO, ST_REGISTRO_ATIVO) VALUES(4, 1, 'AII', 'S');



